# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: create npm and release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: 'npm'
    - run: npm install --no-fund
    - run: npm run build
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

#   release:
#     # needs: publish
#     runs-on: ubuntu-latest
#     steps:
# #     - name: Read package.json
# #       uses: ashley-taylor/read-json-property-action@v1.0
# #       with:
# #           path: './package.json'
# #       id: package-version
#     # - name: Get version
#     #   id: package_version
#     #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

#     - uses: actions/checkout@master
#     - name: Create a Release
#       uses: elgohr/Github-Release-Action@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

